name: schedule_build

on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"

jobs:
  schedule_build:
    permissions:
       content: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: "Install packages"
        run: pip install -r requirements.txt
      - name: "Build image"
        run: python main.py
      - name: Commit and push the generated mosaics
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: preview
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
